### ISSUE TITLE
develop: '$protoWait' of undefined

### ISSUE THREAD

**Issue by MrSwed** [webber12/webixtable#5]
модальное редактирование не работает. в общем весь модуль упал..

после добавления в шаблон main.tpl 00b39fc74831bc0a059d4029789c3fba2053cc37

на старых шаблонах работает нормально

**Comment by webber12** [comment]
Да, полторы строчки не донес - https://github.com/webber12/webixtable/commit/882bc8df2c81164df45e4484c2180e6097301a23 :)
